### ISSUE TITLE
Env

### ISSUE THREAD

**Issue by luoww1992** [yingfengwu/nao_motion_imitation#1]
what is your env ?
and i am wrong when pybullet.loadURDF(URDF_FILENAME...).

b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 000000000000093C
MotionThreadFunc thread started
b3Printf: b3Warning[C:\Users\admin\AppData\Local\Temp\pip-install-seh5rbr4\pybullet_762d617ac3af4817beafc9a33dffed1c\examples\Importers\ImportURDFDemo\UrdfFindMeshFile.h,102]:

b3Printf: D:\addPackageSelf\PycharmProjects\HumanAction\ReTarGet\nao_motion_imitation\retarget_motion\robot_data\nao.urdf:73: cannot find 'meshes/nao/HeadYaw.obj' in any directory in urdf path

Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: Could not parse visual element for Link:
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: Neck
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

robot = pybullet.loadURDF(URDF_FILENAME, 
pybullet.error: Cannot load URDF file.

**Comment by yingfengwu** [comment]
You should download the nao.urdf in the softbank website.

**Comment by luoww1992** [comment]
the nao.urdf in your project is wrong ?
----- 原始邮件 -----
发件人：yingfengwu ***@***.***>
收件人：yingfengwu/nao_motion_imitation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1)
日期：2023年06月27日 14点08分


You should download the nao.urdf in the softbank website.

&mdash;

**Comment by luoww1992** [comment]
if i use other skeleton bvh, 
can i use it to retarget ? if yes, how to change the one-to-one skeleton in code ?
----- 原始邮件 -----
发件人：yingfengwu ***@***.***>
收件人：yingfengwu/nao_motion_imitation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1)
日期：2023年06月27日 14点08分


You should download the nao.urdf in the softbank website.

&mdash;

**Comment by yingfengwu** [comment]
There are no any errors in my before pc. Based on your error message, maybe the path is wrong or some files are lost.

**Comment by luoww1992** [comment]
i have download a new nao.urdf but have the same question
----- 原始邮件 -----
发件人：yingfengwu ***@***.***>
收件人：yingfengwu/nao_motion_imitation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1)
日期：2023年06月27日 14点08分


You should download the nao.urdf in the softbank website.

&mdash;

**Comment by luoww1992** [comment]
this is my shows:

pybullet build time: Jun 27 2023 14:44:02
starting thread 0
started testThreads thread 0 with threadHandle 0000000000000260
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
Version = 4.6.0 NVIDIA 516.94
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 0000000000000944
MotionThreadFunc thread started
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: Error=XML_ERROR_PARSING_ATTRIBUTE ErrorID=8 (0x8) Line number=16: XMLElement name=link
Traceback (most recent call last):
  File "D:\ReTarGet\nao_motion_imitation\retarget_motion\run_nao_retarget.py", line 473, in <module>
    main(txt_dict)
  File "D:\ReTarGet\nao_motion_imitation\retarget_motion\run_nao_retarget.py", line 423, in main
    ground = pybullet.loadURDF(GROUND_URDF_FILENAME)
pybullet.error: Cannot load URDF file.
numActiveThreads = 0
stopping threads
Thread with taskId 0 with handle 0000000000000944 exiting
Thread TERMINATED
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 with handle 0000000000000260 exiting
Thread TERMINATED
----- 原始邮件 -----
发件人：yingfengwu ***@***.***>
收件人：yingfengwu/nao_motion_imitation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1)
日期：2023年06月27日 14点48分


There are no any errors in my before pc. Based on your error message, maybe the path is wrong or some files are lost.

&mdash;

**Comment by luoww1992** [comment]
can you share  your twos urdf files, i have try it many times by download new  file, but it is also wrong
----- 原始邮件 -----
发件人：yingfengwu ***@***.***>
收件人：yingfengwu/nao_motion_imitation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1)
日期：2023年06月27日 14点48分


There are no any errors in my before pc. Based on your error message, maybe the path is wrong or some files are lost.

&mdash;

**Comment by luoww1992** [comment]
Sucessfully, i have see the file content, i find it dependents on some files, 
then i run it sucessfully ！
=============================
Q1, these are 15 joints, if more, can it run ? if yes, how to change the code.? change the index of bone ?
Q2, if i use other human urdf file, how to change it ? 
Q3, if the nao.urdf gets 2 times bigger than before, the result is OK ?
----- 原始邮件 -----
发件人：yingfengwu ***@***.***>
收件人：yingfengwu/nao_motion_imitation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1)
日期：2023年06月27日 14点48分


There are no any errors in my before pc. Based on your error message, maybe the path is wrong or some files are lost.

&mdash;

**Comment by luoww1992** [comment]
Q4, how to clean up the footskate ?
----- 原始邮件 -----
发件人：yingfengwu ***@***.***>
收件人：yingfengwu/nao_motion_imitation ***@***.***>
抄送人：luoww1992 ***@***.***>,  Author ***@***.***>
主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1)
日期：2023年06月27日 14点48分


There are no any errors in my before pc. Based on your error message, maybe the path is wrong or some files are lost.

&mdash;

**Comment by starlin0418** [comment]
> Sucessfully, i have see the file content, i find it dependents on some files, then i run it sucessfully ！ ============================= Q1, these are 15 joints, if more, can it run ? if yes, how to change the code.? change the index of bone ? Q2, if i use other human urdf file, how to change it ? Q3, if the nao.urdf gets 2 times bigger than before, the result is OK ? ----- 原始邮件 ----- 发件人：yingfengwu ***@***.***> 收件人：yingfengwu/nao_motion_imitation ***@***.***> 抄送人：luoww1992 ***@***.***>, Author ***@***.***> 主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1) 日期：2023年06月27日 14点48分 There are no any errors in my before pc. Based on your error message, maybe the path is wrong or some files are lost. &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>



> can you share your twos urdf files, i have try it many times by download new file, but it is also wrong ----- 原始邮件 ----- 发件人：yingfengwu ***@***.***> 收件人：yingfengwu/nao_motion_imitation ***@***.***> 抄送人：luoww1992 ***@***.***>, Author ***@***.***> 主题：Re: [yingfengwu/nao_motion_imitation] Env (Issue #1) 日期：2023年06月27日 14点48分 There are no any errors in my before pc. Based on your error message, maybe the path is wrong or some files are lost. &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>



> what is your env ? and i am wrong when pybullet.loadURDF(URDF_FILENAME...).
> 
> b3Printf: Selected demo: Physics Server starting thread 0 started MotionThreads thread 0 with threadHandle 000000000000093C MotionThreadFunc thread started b3Printf: b3Warning[C:\Users\admin\AppData\Local\Temp\pip-install-seh5rbr4\pybullet_762d617ac3af4817beafc9a33dffed1c\examples\Importers\ImportURDFDemo\UrdfFindMeshFile.h,102]:
> 
> b3Printf: D:\addPackageSelf\PycharmProjects\HumanAction\ReTarGet\nao_motion_imitation\retarget_motion\robot_data\nao.urdf:73: cannot find 'meshes/nao/HeadYaw.obj' in any directory in urdf path
> 
> Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
> 
> Warning: Could not parse visual element for Link: Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
> 
> Warning: Neck Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:
> 
> robot = pybullet.loadURDF(URDF_FILENAME, pybullet.error: Cannot load URDF file.

您好！我也和您有一样的报错，想请问一下您需要安装哪些files才能得以解决呀？

**Comment by starlin0418** [comment]
b3Printf: b3Warning[C:\Users\starlin\AppData\Local\Temp\pip-install-kta03k46\pybullet_c94bbb5a2c894da4866766d70fa03390\examples\Importers\ImportURDFDemo\UrdfFindMeshFile.h,102]:

b3Printf: C:/Users/starlin/Desktop/nao_motion_imitation-master/retarget_motion/robot_data/nao.urdf:73: cannot find 'meshes/nao/HeadYaw.obj' in any directory in urdf path

Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: Could not parse visual element for Link:
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: Neck
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

这是我的报错内容，想请问一下是由于缺少meshes文件嘛？我安装qibullet包之后的meshes文件夹是加密的，installer文件打开之后发生闪退。我不知道如何下载meshes文件夹，想请求一下您的帮助！
